pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        sh 'pip install -r /Receiver/requirements.txt'
      }
    }
    stage('Lint') {
      steps {
        sh 'pylint-fail-under --fail_under 5.0 *.py'
      }
    }
  }
}
